### PR TITLE
MAINTAINERS: add @bonifaido

### PR DESCRIPTION
**Pull request by srenatus**
Following the suggestion in #1485. Let's add @bonifaido 🎉 👏

### CODE REVIEW

**Comment by srenatus** [comment]
I'll update github settings when we've approved/merged this.

**Comment by srenatus** [comment]
@bonifaido you should have gotten an invite link

**Comment by bonifaido** [comment]
Just accepted it, thank you very much!

**Comment by rithujohn191** [comment]
Welcome @bonifaido :)

**Pull request merged**
