### PR TITLE
Setting email for OpenShift connector

### PR DESCRIPTION
**Pull request by sabre1041**
Automatically sets the email field to be based on the username for the OpenShift connector

### CODE REVIEW

**Comment by sabre1041** [comment]
Any chance the CI can be rerun? Appears to have failed due to a timeout

**Comment by bonifaido** [comment]
Yes, just kicked it 👞

**Comment by bonifaido** [comment]
Somehow the build can't pick up this commit from your remote, have you force pushed it (possibly)? Even that shouldn't cause an issue like this...

**Comment by sabre1041** [comment]
Yes I did force push after squashing commits. but as you mentioned,  this should not cause an issue.

I can start over and re point this pr at a new branch or new pr

**Comment by bonifaido** [comment]
Can you please rebase on master now? I think the issue was because GitHub actions recently updated the checkout action, and we used the previous version.

**Comment by sabre1041** [comment]
@bonifaido I opened up #1661 which used latest master as I didnt get the your message notification in time :(

**Pull request closed without merging**
