### PR TITLE
Update ent

### PR DESCRIPTION
**Pull request by sagikazarmark**
#### Overview

Update ent to the latest version.

#### What this PR does / why we need it

Updates the ent library to the latest version as well as opts-in for the new Atlas migration engine and regenerates generated files.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by sagikazarmark** [comment]
@nabokihms any ideas what's going wrong here?

**Comment by nabokihms** [comment]
I have never seen this before. If you want, I can research the actual cause.

**Comment by sagikazarmark** [comment]
Looking at the error, the returned timestamp is not precise enough. I don't know if that's because of ent or something else.

**Comment by sagikazarmark** [comment]
Looks like the problem was with Atlas. I disabled it for now.

See the linked issue for details.

**Comment by sagikazarmark** [comment]
I don't know what's with the Docker build these days.

**Comment by sagikazarmark** [comment]
@nabokihms can I get a review on this one? I managed to fix the tests. Docker is just...doing it's own thing, I'm gonna ignore that.

**Review by nabokihms — APPROVED** [review]
Looks perfect! Thank you.

**Pull request merged**
