### PR TITLE
Rework - add support for Resource Owner Password Credentials Grant

### PR DESCRIPTION
**Pull request by xtremerui**
As per comment https://github.com/dexidp/dex/pull/1163#issuecomment-572975220, this PR from [ConcourseCI](https://github.com/concourse) team is a rework of https://github.com/dexidp/dex/pull/1163 since the original PR is outdated and its author allowed us to continue his work. 

cc @pivotal-jwinters 

@bonifaido thanks!

### CODE REVIEW

**Comment by vito** [comment]
Hi, just checking in - any chance this could be merged? Just hoping to gradually shrink the amount of PRs we have open (listed in https://github.com/concourse/concourse/issues/4983#issuecomment-573702806) so we can get off our fork. Thanks if so! :slightly_smiling_face:

**Comment by bonifaido** [comment]
Of, course, sorry for being late on this one.

**Comment by speculatrix** [comment]
How do I make use of this to make "fly -t xx login" work with an ldap username/password?

**Comment by roDew** [comment]
I'm interested in the same too...

**Pull request merged**
