### PR TITLE
chore: fix function name

### PR DESCRIPTION
**Pull request by finaltrip**
#### Overview

fix function name

### CODE REVIEW

**Comment by nabokihms** [comment]
This code is autogenerated I'm afraid.

**Comment by cpanato** [comment]
that is wrong in the template from https://github.com/ent/ent (https://github.com/ent/ent/blob/092b62a3229476d18d9ffade87da268d9136f13a/entc/gen/template/dialect/sql/by.tmpl#L19) we should fix there

**Comment by cpanato** [comment]
PR that fix in upstream: https://github.com/ent/ent/pull/4083

**Comment by finaltrip** [comment]
> PR that fix in upstream: [ent/ent#4083](https://github.com/ent/ent/pull/4083)

Thanks!

**Comment by cpanato** [comment]
fixed, maybe we can rebase?

**Comment by finaltrip** [comment]
> fixed, maybe we can rebase?

Updated. Please review again.

**Comment by nabokihms** [comment]
There are no changes in this PR anymore. Do we still need these two commits to be merged?

**Comment by cpanato** [comment]
yep we can close it

**Comment by nabokihms** [comment]
Thanks @cpanato

**Pull request closed without merging**
