### PR TITLE
Support customize oidc groups key

### PR DESCRIPTION
**Pull request by xtremerui**
Since groups claim is not a [standard claim in OIDC](https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims), the groups claim name could be something other than "groups". This PR allows dex OIDC connector to take a custom key to look up groups claims.

cc @pivotal-jwinters

### CODE REVIEW

**Comment by ktravis** [comment]
Any ETA on this feature being added in a release?

**Comment by ktravis** [comment]
Gentle bump - Is this still being considered for inclusion?

**Comment by rbtr** [comment]
@sagikazarmark or maybe @bonifaido this would be really nice to have

**Comment by xtremerui** [comment]
I will close this PR as similar feature is done in #1634

**Pull request closed without merging**
