### PR TITLE
Run getUserInfo prior to claim enforcement

### PR DESCRIPTION
**Pull request by jacksontj**
If you have an oidc connector configured *and* that IDP provides thin
tokens (e.g. okta) then the majority of the requested claims come in the
getUserInfo call (such as email_verified). So if getUserInfo is
configured it should be run before claims are validated.

### CODE REVIEW

**Comment by jacksontj** [comment]
cc @JoelSpeed @srenatus

**Comment by srenatus** [comment]
Thank you 🎈 🎉

**Comment by jacksontj** [comment]
@srenatus whats left to get this merged?

**Comment by jacksontj** [comment]
Friendly bump :)

@srenatus @JoelSpeed

**Comment by bonifaido** [comment]
Looks good, so merging it :)

**Pull request merged**
