### PR TITLE
refactor: move from io/ioutil to io and os package

### PR DESCRIPTION
**Pull request by Juneezee**
#### Overview

The `io/ioutil` package has been deprecated in Go 1.16 (See https://golang.org/doc/go1.16#ioutil). This PR replaces the existing `io/ioutil` functions with their new definitions in `io` and `os` packages.

#### What this PR does / why we need it

> The io/ioutil package has turned out to be a poorly defined and hard to understand collection of things. -- https://golang.org/doc/go1.16#ioutil

> Avoid meaningless package names. Packages named util, common, or misc provide clients with no sense of what the package contains. -- https://go.dev/blog/package-names

The Golang team has decided to deprecate the `io/ioutil` package and recommends new code to use the new definitions. To avoid inconsistency in the future, it is a good idea to move all current usage of `io/ioutil` functions to the new definitions.

#### Special notes for your reviewer
No breaking changes.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by nabokihms — CHANGES_REQUESTED** [review]
Good catch, thanks!

I think that to consolidate what you have done there, we need to setup a depguard linter to prevent others from using the `ioutil` package.

It is possible by adding the following block to the .golangci.yml in the repo root:
```yaml
linters-settings:
  depguard:
    list-type: blacklist
    include-go-root: true
    packages:
    - io/ioutil
    packages-with-error-message:
    - io/ioutil: "The 'io/ioutil' package is deprecated. Use corresponding 'os' or 'io' functions instead."
```
and enabling the depguard linter.

**Comment by Juneezee** [comment]
@nabokihms Hi! Thanks for reviewing the pull request. I have added the depguard linter. Please take a look again. Thanks

**Comment by nabokihms** [comment]
You should also enable the `depguard` linter in the `linters.enable` section (it is commented right now).

**Comment by Juneezee** [comment]
@nabokihms Sorry, my bad. depguard should be enabled now.

**Review by sagikazarmark — APPROVED** [review]
LGTM, thanks!

**Review by nabokihms — APPROVED** [review]

**Pull request merged**
