### PR TITLE
[fix] Replace /teams API w/ /workspaces endpoints

### PR DESCRIPTION
**Pull request by rahulchheda**
Signed-off-by: Rahul M Chheda <rahul.chheda@accurics.com>

#### Overview

Bitbucket's `/teams` endpoint is now decrecated: https://developer.atlassian.com/cloud/bitbucket/rest/api-group-teams/#api-teams-get

#### What this PR does / why we need it
Resolves: https://github.com/dexidp/dex/issues/2391

#### Special notes for your reviewer
Not a lot of changes here.

#### Does this PR introduce a user-facing change?
Nope

```release-note
- Replace `/teams` API w/ `/workspaces`
```

### CODE REVIEW

**Comment by rahulchheda** [comment]
Resolves: https://github.com/dexidp/dex/issues/2391

**Comment by nabokihms** [comment]
I will take a look soon. 

Previously, I worked on this PR https://github.com/dexidp/dex/pull/2023, but we haven't merged it, and I don't remember why.

**Comment by JanisOrlovs** [comment]
Hello,
This is pretty big problem for us as we use bitbucket to login to ArgoCD with dex. What is expected timeline for fix?

**Comment by nabokihms** [comment]
@JanisOrlovs because we have no integration tests for most provider-specific connectors, e.g., Gitlab. Bitbucket, we need to do manual tests before merging it. I would say ETA is 1-2 days.

**Review by nabokihms — APPROVED** [review]
As far as I can tell, everything works fine except the `includeTeamsGroups` option, but it seems this option doesn't work correctly anyway (see #https://github.com/dexidp/dex/issues/1977).

LTGM.

**Pull request merged**
