### PR TITLE
feat: gotemplate formatting for Dex config file

### PR DESCRIPTION
**Pull request by nabokihms**
Signed-off-by: m.nabokikh <maksim.nabokikh@flant.com>

#### Overview
* read config file as a template and execute it
* add [sprig function](http://masterminds.github.io/sprig/) support
* provide template configuration example

#### What this PR does / why we need it
An alternative of #1893
Instead of adding an external tool (dockerize), this PR introduces another approach.

#### Does this PR introduce a user-facing change?
```release-note
Add go template formatting support for Dex config file.
```

### CODE REVIEW

**Comment by sagikazarmark** [comment]
I'm **very** much against this approach. This shouldn't be Dex's responsibility. Dockerize indeed seems to be a dead end, so I see two ways ahead:

- Fork/rewrite dockerize: the community needs a project like this IMO anyway
- Try [gotemplate](https://github.com/hairyhenderson/gomplate) (suggested in https://github.com/dexidp/dex/issues/1838#issuecomment-719424256): we don't use anything other than template generation.

**Comment by nabokihms** [comment]
Just an example, we can close this PR after figuring out the right way.

**Comment by nabokihms** [comment]
Personally, I'm more into gomplate, than rewriting dockerize (or rewriting anything).
* arm packages
* Crypto functions
* YAML formatting function
* Solid doccumentation

**Comment by sagikazarmark** [comment]
I think we can close this in favor of #1893

**Pull request closed without merging**
