### PR TITLE
abort connector login if connector was already set #1707

### LINKED ISSUE #1707: Overwriting already chosen connector in auth request should not be possible
Suppose the following scenario:

1) "Choose connector" page is shown
2) User chooses connector_1 => UpdateAuthRequest is issued to storage with connector_1 data
3) User authenticates with connector_1, approval form is shown
4) If user now sends another "choose connector" call to /auth/connector_2 it allows to change AuthRequest.connector_id field to connector_2's id
5) User approves form from step 3) => Authcode is created with Data from connector_1 but authCode.ConnectorID is set to connector_2 id

This introduces data inconsistencies in the db and should be disallowed

### PR DESCRIPTION
**Pull request by tkleczek**
Fixes #1707

### CODE REVIEW

**Review by JoelSpeed — APPROVED** [review]
I think this makes sense, thanks for the fix!

**Comment by JoelSpeed** [comment]
One of the PR status's is pending, not really sure why that is, @tkleczek do you fancy rebasing and pushing over this branch to get the tests to re-run?

**Comment by tkleczek** [comment]
@JoelSpeed: I did a rebase, should be good to merge

**Review by sagikazarmark — APPROVED** [review]
lgtm, thanks

**Pull request merged**
