### PR TITLE
Option to add staticPasswords from environment variables

### PR DESCRIPTION
**Pull request by krishnadurai**
This PR introduces the ability to set StaticPasswords with field 'hashFromEnv'.

Partially implements requirements from #1099.

Relates to kubeflow/kfctl#130

/cc @ericchiang @rithujohn191 @sagikazarmark @bonifaido

### CODE REVIEW

**Comment by krishnadurai** [comment]
@ericchiang @rithujohn191 @sagikazarmark @bonifaido could any one of you PTAL?

**Comment by krishnadurai** [comment]
Circling back in here again to see if we could please get this reviewed once.

@ericchiang @rithujohn191 @sagikazarmark @bonifaido

**Comment by ericchiang** [comment]
I am no longer a dex maintainer. Please stop cc'ing me :)

**Comment by sagikazarmark** [comment]
@krishnadurai we've received your PR, but as the holidays are coming, it probably won't be reviewed until next year.

**Comment by krishnadurai** [comment]
@sagikazarmark thanks for replying. Sorry for being impatient about it. We could wait until the holidays end. :-)

**Comment by krishnadurai** [comment]
@sagikazarmark this is ready for a look.

**Comment by krishnadurai** [comment]
@sagikazarmark Could we please move this PR forward?

**Comment by sagikazarmark** [comment]
@krishnadurai I've looked at your PR, it looks OK implementation-wise, but I'm not sure I would ever use this feature from an operational standpoint.

Managing users in a static file already presents a lot of limitations and issues (eg. security) and I understand this is an attempt improve that last bit, but I'm not 100% it's actually an improvement.

Can you tell me a bit more about how you imagine using this feature? Or in what cases would you consider recommending it?

Thanks!

**Comment by k0da** [comment]
I'd love to have this feature, so far we awaited for such feature to move secrets into k8s secretes, k8s secrets are perfectly managed by kustomize and vault plugin.

Of course, better option would be an operator, but I'm not aware of any existing yet.

**Comment by krishnadurai** [comment]
@sagikazarmark We use Dex in [Kubeflow](kubeflow.org). One of our setups is a basic authentication - based setup. We are keen on using staticPasswords field for setting up basic auth with Dex for Kubeflow.
The challenge with the configuration file, as you've mentioned, is that the credentials are exposed. In Kubeflow we have a 'KfDef' based yaml definition, as shown in this [file](https://github.com/kubeflow/manifests/blob/master/kfdef/kfctl_istio_dex.yaml).

Lines
https://github.com/kubeflow/manifests/blob/9aae81d93b78b3fe802527b084530672f39e2b1a/kfdef/kfctl_istio_dex.yaml#L112-L113

Show that this committed configuration has secrets.

We are looking to accept environment variables through our deployment plugin ([kubeflow/kfctl](https://github.com/kubeflow/kfctl)) which would set this environment variable on the Dex controller pod programmatically.

**Comment by krishnadurai** [comment]
@sagikazarmark thanks for considering it @sagikazarmark!

**Comment by krishnadurai** [comment]
@bonifaido It looks like this requires your review as well. Could you please take a look?

**Pull request merged**
