### PR TITLE
MAINTAINERS: drop @srenatus

### PR DESCRIPTION
**Pull request by srenatus**
This reflects that I currently don't have time to contribute to this fine
project. It's been fun, thanks a lot to all the current and past maintainers!

### CODE REVIEW

**Review by justaugustus — APPROVED** [review]
Thanks so much for all of your work in project, @srenatus! :two_hearts: 

FYI @dexidp/maintainers.

**Comment by srenatus** [comment]
@dexidp/maintainers would you please take care of removing any privileged access I may have on the repo? Thanks! 🎉

**Comment by sagikazarmark** [comment]
Thanks a lot for your work @srenatus!

I can't see you having any privileged access (maybe someone took care of it?).

**Comment by justaugustus** [comment]
Yep, just finished cleaning up :)

**Comment by srenatus** [comment]
Thank you! 🚀

**Pull request merged**
