### PR TITLE
connectors/oidc: truely ignore "email_verified" claim if configured that way

### LINKED ISSUE #1455: OIDC connector insecureSkipEmailVerified flag is not used
The documentation says:

> Some providers return claims without "email_verified", when they had no usage of emails verification in enrollement process or if they are acting as a proxy for another IDP etc AWS Cognito with an upstream SAML IDP
> This can be overridden with the below option
> insecureSkipEmailVerified: true 

But if "email_vierified" claim is missing the flag is never checked. It works only if the field exists and has boolean value. The code responsible for it is in here: https://github.com/dexidp/dex/blob/49e59fb54fb308c2cb17508232c28073964d3e35/connector/oidc/oidc.go#L220-L242

The configuration check should be moved up and claim `email_vierified` should not be retrieved if the flag is set to `true`

### PR DESCRIPTION
**Pull request by srenatus**
Fixes #1455, I hope.

### CODE REVIEW

**Comment by srenatus** [comment]
Looks like I'll look into travis first. Likely ditching support for golang 1.10. 🤔

**Comment by srenatus** [comment]
@pbochynski thank you so much for verifying. I'll merge this when I've dealt with the travis issue...

**Comment by srenatus** [comment]
https://github.com/dexidp/dex/pull/1457

**Comment by srenatus** [comment]
@JoelSpeed @ericchiang This is rather trivial, and @pbochynski has been so kind to review it -- so, I'll pull the admin string to _still merge this pull request_. LMK if you think I shouldn't have. 😉

**Comment by JoelSpeed** [comment]
Looks ok to me :)

**Comment by Amorn-Kingthong** [comment]
Leave a comment i will go

**Pull request merged**
