### PR TITLE
enable custom Azure endpoints for Government Cloud Services customers

### PR DESCRIPTION
**Pull request by jlane67**
#### Overview

Stops hard-coding Azure endpoints as they are not universally accurate.

#### What this PR does / why we need it

Resolves https://github.com/dexidp/dex/issues/2457.  Pure OIDC mode is unable to retrieve group membership data from Azure AD, meaning RBAC is impossible.

#### Does this PR introduce a user-facing change?

yes

```release-note
This change makes the Azure endpoints configurable.  For most users, the default 
https://login.microsoftonline.com/ and https://graph.microsoft.com/ values 
will remain the correct choice, but this allows users of Azure in special 
regions, such as Government Cloud Services for export-controlled workloads, 
to use the Microsoft connector to get group membership.
```

### CODE REVIEW

**Comment by sagikazarmark** [comment]
@jlane67 thanks for the contribution!

On the surface, this seems to be a breaking change as the default values for those URLs are empty strings.

Do you know if the underlying library falls back to the right default values in this case? Can you also point to the code in the SDK?

Last, but not least: can you please update the documentation? https://github.com/dexidp/website/blob/main/content/docs/connectors/microsoft.md

**Comment by jlane67** [comment]
Hi, thank you for pointing that out.  I have added another commit adding a fallback to the default values.  I'm not super experienced at Go, but this is just something that came up in the course of deploying Dex.  If the logical flow looks good I can add a PR to fix the documentation.

**Comment by jlane67** [comment]
I have confirmed in a deployment on our infrastructure that the changes in this PR allow full authentication with Azure Government Cloud Services when using the .us endpoints.

**Comment by sleterrier** [comment]
@sagikazarmark: anything I could do to help this PR get merged?

**Comment by dsetlock** [comment]
@sagikazarmark wanting to pick this thread back up. Trying to deploy Dex into Azure Government I hit this same blocker and came here to investigate but it seems a PR has been make the Azure endpoints more flexible for over a year.

**Comment by sagikazarmark** [comment]
I'm looking at the code and....I'm a little bit confused. I don't think this code even compiles.

**Pull request closed without merging**
