### PR TITLE
chore: Upgrade golangci-lint to v1.50.1 from v1.46.0

### PR DESCRIPTION
**Pull request by dlipovetsky**
#### Overview

Updates the version of golangci-lint defined in the Makefile.

#### What this PR does / why we need it

Versions prior to v1.48.0 are incompatible with go v1.19, which is in use since d33e9948059abe45257cc6b734870b2c4f3c4ea5.

Linting fails:

```console
❯ go version
go version go1.19.2 linux/amd64

❯ make bin/golangci-lint
curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | BINARY=golangci-lint bash -s -- v1.46.0
golangci/golangci-lint info checking GitHub for tag 'v1.46.0'
golangci/golangci-lint info found version: 1.46.0 for v1.46.0/linux/amd64
bgolangci/golangci-lint info installed ./bin/golangci-lint

❯ bin/golangci-lint run
panic: load embedded ruleguard rules: rules/rules.go:13: can't load fmt

goroutine 1 [running]:
github.com/go-critic/go-critic/checkers.init.22()
	github.com/go-critic/go-critic@v0.6.3/checkers/embedded_rules.go:47 +0x4b4
```

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by nabokihms** [comment]
@dlipovetsky thank you for opening this PR. The new version of linter found some errors that should be fixed. Could you please take a look when you have time?

**Comment by dlipovetsky** [comment]
Sorry, I accidentally rebased on master and included two dependabot commits. Removing those and force-pushing.

**Comment by dlipovetsky** [comment]
Some linter warnings remain, but they don't need to be fixed right away:

```console
❯ bin/golangci-lint run
WARN [runner] The linter 'varcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused. 
WARN [runner] The linter 'deadcode' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused. 
WARN [runner] The linter 'structcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused. 
WARN [linters_context] rowserrcheck is disabled because of generics. You can track the evolution of the generics support by following the https://github.com/golangci/golangci-lint/issues/2649. 
WARN [linters_context] sqlclosecheck is disabled because of generics. You can track the evolution of the generics support by following the https://github.com/golangci/golangci-lint/issues/2649. 
WARN [linters_context] structcheck is disabled because of generics. You can track the evolution of the generics support by following the https://github.com/golangci/golangci-lint/issues/2649. 
```

I'll address those in a separate PR.

**Comment by dlipovetsky** [comment]
On second thought, removing the deprecated linters is straightforward; there were no "nolint" directives. I added a commit to this PR.

I also added a commit to re-enable the `typecheck` linter, since it seems to be working correctly again.

The remaining warnings are about disabled linters:
```console
❯ bin/golangci-lint run
WARN [linters_context] rowserrcheck is disabled because of generics. You can track the evolution of the generics support by following the https://github.com/golangci/golangci-lint/issues/2649. 
WARN [linters_context] sqlclosecheck is disabled because of generics. You can track the evolution of the generics support by following the https://github.com/golangci/golangci-lint/issues/2649. 
```

**Review by nabokihms — APPROVED** [review]
LGTM. Thank you for your work @dlipovetsky.

**Pull request merged**
