### PR TITLE
[WIP] Removing .md files as a part of the Dex IdP Documentation migration.

### PR DESCRIPTION
**Pull request by hackabletype**
As per issue https://github.com/dexidp/dex/issues/1761, the .md files are being removed from the Documentation folder and are being moved into the [dexidp/website](https://github.com/dexidp/website), see [PR #8](https://github.com/dexidp/website/pull/8) for the other part of this migration work.

Images and logos remain as they are  being referenced by the main README.md file.

I think we should wait to merge this PR until the dexidp/website [PR #8](https://github.com/dexidp/website/pull/8) is merged for continuity of documentation availability. *Note*, the new URLs in the main README.md file point to where the site will eventually live, so we may not want to merge this until we at least get the site up and the URL redirected.

I'm not yet able to add reviewers, so @-mentioning: @justaugustus @celestehorgan @sagikazarmark @JoelSpeed

### CODE REVIEW

**Review by bonifaido — APPROVED** [review]
LGTM

**Comment by sagikazarmark** [comment]
I agree, we should wait until the website is up.

@hackabletype AFAIR we agreed to use the dexidp.io domain, so can you please update the links? Thanks!

**Comment by hackabletype** [comment]
I’m getting a Docker error in the auto checker, something about a password not being supplied.
I expect that it’s something to do with the .github/workflows/ci.yml file, the dockerhub logins are a part of the repos secrets, and as a non-contributor github is probably not automatically providing them (just a thought, but I’m not sure)

Is this something I need to be concerned about for this PR?

**Comment by hackabletype** [comment]
@bonifaido, @sagikazarmark, since dexidp/website PR https://github.com/dexidp/website/pull/8 has been merged, this PR is ready for review.

**Comment by sagikazarmark** [comment]
> Is this something I need to be concerned about for this PR?

@hackabletype Nope. (But it's been fixed on master, so rebasing should fix it)

**Review by sagikazarmark — APPROVED** [review]
Thanks @hackabletype

**Pull request merged**
