### PR TITLE
add @sagikazarmark to MAINTAINERS

### PR DESCRIPTION
**Pull request by bonifaido**
I would like to add Mark to the maintainers, he has already contributed to the project, and with more maintainers, we probably could speed up the project a little bit again! 💯

### CODE REVIEW

**Comment by bonifaido** [comment]
Thanks! Yeah, I just asked for other people to join as well, like here https://github.com/dexidp/dex/issues/1593#issuecomment-562508800 ;) Maybe we need to create an issue for the case!

**Comment by sagikazarmark** [comment]
Thanks @srenatus ! I hope I can be a valuable maintainer. 🙂

**Comment by bonifaido** [comment]
@srenatus could you please give @sagikazarmark write access to the repo to be able to create branches and code reviews?

Thanks in advance! 👍

**Comment by srenatus** [comment]
@bonifaido you should be able to do that now 😉

**Comment by bonifaido** [comment]
Thank you! :tada:

**Pull request merged**
