### PR TITLE
storage/kubernetes: Removing Kubernetes TPR support

### PR DESCRIPTION
**Pull request by venezia**
Part of fixing #1513 - this has a significant amount of code change and wanted to push this through before adding a flag to CRD creation.

### CODE REVIEW

**Comment by srenatus** [comment]
I'll defer to @JoelSpeed on this one 😉

**Comment by venezia** [comment]
> No one should be using TPRs anymore as Kubernetes introduced CRDs about 2 years ago. I would however be tempted to leave the migration instructions for 1 release after we remove the code. If you haven't already migrated and we remove the migration instructions, you'll be a bit stuck!
> 
> Can we keep the migration instructions and add a TODO to remove them after the next release?

In this PR there is [a link](https://github.com/venezia/dex/blob/iss-1513/Documentation/storage.md#removed-kubernetes-third-party-resourcestprs) in the storage docs to v2.17.0 as the last version to support TPR.  If we're removing support for TPR in the next release, perhaps instead of keeping the migration instructions in the current documentation we simply add another line with a link to [the old migration documentation](https://github.com/dexidp/dex/blob/v2.17.0/Documentation/storage.md#migrating-from-tprs-to-crds) ... and either remove `scripts/dump-tprs` or have that in the TODO to remove.

I could see it either way, just let me know

**Comment by JoelSpeed** [comment]
@venezia You make a very good point, how about we just add a link to the old migration documentation saying something like "Note: If you have not migrated away from TPRs, please see the [documentation] and migrate before upgrading Dex"

**Comment by venezia** [comment]
@JoelSpeed I updated the documentation a bit, removed the legacy script, squashed commits and force pushed back to my branch.

LMK if this works for you - thanks!

**Comment by srenatus** [comment]
Just for the record, I've been publishing a release while you've been discussing this. So, whatever was true for TPR in 2.17.0 probably is true for 2.18.0 as well 😄

**Comment by venezia** [comment]
hah - well that's the breaks :)

**Comment by JoelSpeed** [comment]
>Just for the record, I've been publishing a release while you've been discussing this. So, whatever was true for TPR in 2.17.0 probably is true for 2.18.0 as well 😄

I don't think this should cause an issue, the docs have been removed and people should notice it stopping working eventually 🤷‍♂

**Pull request merged**
