### PR TITLE
Adding Power support 

### PR DESCRIPTION
**Pull request by ghatwala**
Created this PR as suggested here - https://github.com/dexidp/dex/issues/1388#issuecomment-458518798 .

@srenatus  - can you please comment.

### CODE REVIEW

**Comment by ericchiang** [comment]
hmm, this is a problem, our CI uses docker

```
Error response from daemon: Could not kill running container ee3a720629ca2d3aec7c98c63923ed99af2b2fb0c04fa5928f01da40a8573d16, cannot remove - Cannot kill container ee3a720629ca2d3aec7c98c63923ed99af2b2fb0c04fa5928f01da40a8573d16: unknown error after kill: docker-runc did not terminate sucessfully: container_linux.go:393: signaling init process caused "permission denied"
```

Maybe we should skip integration tests on other architectures?

**Comment by ghatwala** [comment]
@ericchiang  - thanks for pointing that out . seems like there's a fix for this issue of container deletion related to  "apparmor"  as given here - https://stackoverflow.com/questions/47223280/docker-containers-can-not-be-stopped-or-removed-permission-denied-error. 

Trying to check if this option can help , or else skipping the integration tests on ppc64le would be the easiest fix here.

**Comment by ghatwala** [comment]
@ericchiang @srenatus - please comment and check if this can be merged ?

**Comment by ghatwala** [comment]
@ericchiang @srenatus - please lemme know if anything is pending in this PR ?

**Comment by srenatus** [comment]
I'm on parental leave right now and unable to review this, sorry. 😉

**Comment by ghatwala** [comment]
Happy parenting and welcome to sleepless nights - @srenatus !!!

**Comment by srenatus** [comment]
Are you still interested or have you gotten some workaround? It's been a while... 😉

**Comment by ghatwala** [comment]
hey @srenatus , i am interested ...let me know th way forward here ?

**Comment by ezeeyahoo** [comment]
Is there a roadmap to merge and release image for PPC64LE on quay.io?
Thanks

**Comment by sagikazarmark** [comment]
Unfortunately this PR as it is cannot be merged. It's also not on the roadmap, but PRs are welcome. Please note that quay.io no longer receives updates. See the release notes for details.

**Pull request closed without merging**
