### PR TITLE
OpenShift connector

### PR DESCRIPTION
**Pull request by sabre1041**
Support for authenticating against OpenShift

### CODE REVIEW

**Comment by sabre1041** [comment]
Failed build unrelated to changes introduced by this feature

**Comment by bonifaido** [comment]
Could you please fix the formatting? (I just reran the tests and they seem to be okay now):

`The following files are not formatted correctly: connector/openshift/openshift_test.go`

**Comment by sabre1041** [comment]
@bonifaido corrected errors in tests

**Comment by sabre1041** [comment]
@bonifaido added to list of connectors

**Comment by sabre1041** [comment]
@bonifaido I am improving the security model today and will advise when it should be good to review again

**Comment by sabre1041** [comment]
@bonifaido PR should be ready to merge upon your review again

**Comment by sabre1041** [comment]
@bonifaido any chance you would be able to review?

**Comment by bonifaido** [comment]
Yes, just got the chance again, sorry for the delay (holiday time!).

**Comment by bonifaido** [comment]
And thanks for the PR, nicely done! 👍

**Pull request merged**
