### PR TITLE
Issue 1347 - Gitlab connector should not require the api scope.

### PR DESCRIPTION
**Pull request by gypsydiver**
#1347

### CODE REVIEW

**Comment by srenatus** [comment]
Update -- I've read #1347 again. So, this is meant to use the simpler way, with a less permissive scope? If so, 👍

Still interested in the user-facing changes, if there are any.

**Comment by gypsydiver** [comment]
Changes here would break applications that don't have the `openid` scope enabled and require to pull groups from Gitlab. Admins need to at least enable it in the Gitlab Application settings for groups to work; and ideally disable the `api` (though not required).

**Comment by srenatus** [comment]
👍 sounds great. Do you happen to know when that feature as introduced into Gitlab?

**Comment by gypsydiver** [comment]
[Gitlab CE](https://github.com/gitlabhq/gitlabhq/blob/master/CHANGELOG.md#900-2017-03-22) Version 9.0.0, 2017-03.

**Comment by srenatus** [comment]
Thanks for looking that up. Judging from what, it's been out for more than 18 months, *and* reducing the application scope there is a bit of a significant security improvement, I suppose. I'll merge this.

⏩ Let's make sure to include this information in the next release notes, so nobody is in for a bad surprise.

**Pull request merged**
