### PR TITLE
Addition of Keystone Connector

### PR DESCRIPTION
**Pull request by knangia**
Keystone Connector has been created and added in the list of Dex connectors, to integrate Dex and OpenStack-Keystone, to drive authentication.

### CODE REVIEW

**Comment by knangia** [comment]
hey @ericchiang, want to get this merged.

**Comment by ericchiang** [comment]
@knangia you'll need to resolve the merge conflicts and squash your commits before we review

**Comment by ericchiang** [comment]
(closing and re-opening to kick CI)

**Comment by knangia** [comment]
closing the PR, and uploading a new one, with squashed commits and resolving conflicts

**Pull request closed without merging**
